# fly.toml app configuration file generated for personal-financial-management on 2024-11-29T17:12:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-financial-management'
primary_region = 'nrt'

[build]
  [build.args]
    GO_VERSION = '1.22.7'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
